version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "@typescript-eslint/*"
    open-pull-requests-limit: 10
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - '@typescript-eslint/*'
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
