AllCops:
  Include:
    - '.github/actions/**/*.rb'
    - 'scripts/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Metrics/LineLength:
  Max: 186

Metrics/AbcSize:
  Max: 66

Metrics/MethodLength:
  Max: 59

Style/GlobalVars:
  Exclude:
    - '.github/actions/cleanup-archived-projects/cleanup_projects.rb'
    - '.github/actions/update-stats/update_stats.rb'

