exclude:
  - README.md
  - LICENSE
  - .gitignore
  - CNAME
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - script
  - vendor
  - node_modules
  - netlify.toml

markdown: kramdown
highlighter: rouge
permalink: none

collections:
  projects:
    output: true
    permalink: /projects/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

plugins:
  - jekyll-redirect-from
