desc: A repository of all Dockerfiles in one place to make it easier to find.
name: Dockerfile Archive
site: https://github.com/darkmatter18/dockerfile-archive
stats:
  fork-count: 0
  issue-count: 4
  last-updated: '2022-10-11T14:59:46Z'
tags:
- docker
- dockerfile
- container
- python
- javascript
- cloud
upforgrabs:
  link: https://github.com/darkmatter18/dockerfile-archive/labels/up%20for%20grabs
  name: up for grabs
