on:
  pull_request_target:
    types: [opened, synchronize]

name: Review
jobs:
  reviewProjectChanges:
    name: Project Changes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v6
        with:
          ref: gh-pages
      - name: Setup Ruby
        uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f
        with:
          bundler-cache: true

      - name: Run script to review changed projects
        id: run_script
        run: |
          MESSAGE=$(bundle exec ruby scripts/review_changes.rb --skip-exit-code)
          echo "message: '$MESSAGE'"
          echo 'message<<EOF' >> "$GITHUB_OUTPUT"
          echo "$MESSAGE" >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          GIT_REMOTE_URL: ${{ github.event.pull_request.head.repo.clone_url }}
          GITHUB_TOKEN: ${{ secrets.SHIFTBOT_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0
        with:
          message: ${{ steps.run_script.outputs.message }}
          GITHUB_TOKEN: ${{ secrets.SHIFTBOT_TOKEN }}
